POST http://localhost:9099/product/product-details
Content-Type: application/json

{   
    "name":"150",
    "rate":"5",
    "quantity":"90",
    "brand":"GUCCI",
    "category":"boxers",
    "price":"1200",
    "description":"This is a description for a gucci boxer worth 1200 :)",
    "sizes":"3,12,14",
    "color":"red,blue,yellow",
    "image":"https://cloudinary.com/cloud",
    "weight":"5"
}
###
GET http://localhost:9099/product/all-product
###
GET http://localhost:9099/product/product-info/7c7068cc-bde9-46f7-bf26-3f8f2ea32136
###
POST http://localhost:9099/product/edit-product
Content-Type: application/json

{
    "ide":"7c7068cc-bde9-46f7-bf26-3f8f2ea32136",
    "name":"name",
    "description":"description",
    "amount":"10000"
}
###
POST http://localhost:9099/product/delete-product
Content-Type: application/json
{
    "ide":""
}

###
POST http://localhost:9099/order/order-details
Content-Type: application/json

{
    "firstname":"Chimdindu",
    "lastname":"Ezechukwu",
    "country":"Nigeria",
    "address":"114,alhji amoo street ogudu ojota",
    "city":"Lagos",
    "phone_number":"00000000000",
    "email":"chimdi4332@gmail.com",
    "type":"delivery",
    "company":"non",
    "product":[{"name":"name","size":"3","color":"red","amount":"10000","product_id":"7c7068cc-bde9-46f7-bf26-3f8f2ea32136","quantity":"3"}]
}
###
GET http://localhost:9099/order/all-order-info
###
GET http://localhost:9099/order/order-info/ide