POST http://localhost:9099/product/product-details
Content-Type: application/json

{   
    "name":"150",
    "rate":"5",
    "quantity":"90",
    "brand":"GUCCI",
    "category":"boxers",
    "price":"1200",
    "description":"This is a description for a gucci boxer worth 1200 :)",
    "sizes":"3,12,14",
    "color":"red,blue,yellow",
    "image":"https://cloudinary.com/cloud",
    "weight":"5"
}
###
GET http://localhost:9099/product/all-product
###
GET http://localhost:9099/product/product-info/ide

###
PUT http://localhost:9099/product/edit-product
Content-Type: application/json

{
    "ide":"",
    "name":"name",
    "description":"description",
    "amount":"10000"
}
###
POST http://localhost:9099/product/edit-product
Content-Type: application/json
{
    "ide":"",
    "name":"name",
    "description":"description",
    "amount":"10000"
}